### ISSUE TITLE
Process substitution as file name to redirection is not compiled by shcomp

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#165]
The commands within a process substitution (`<(`...`)` an `>(`...`)`) are simply not included in parse trees dumped by shcomp. This can be verified with a command like `hexdump -C`. As a result, process substitutions don't work when running a bytecode-compiled shell script.

The bug/omission is likely to be somewhere in [`src/cmd/ksh93/sh/tdump.c`](https://github.com/ksh93/ksh/blob/77ab60a149c77f1797a25a43c613dcdb8ad6ce07/src/cmd/ksh93/sh/tdump.c) which is the code for dumping a parse tree into a file. It may be that [`src/cmd/ksh93/sh/trestore.c`](https://github.com/ksh93/ksh/blob/77ab60a149c77f1797a25a43c613dcdb8ad6ce07/src/cmd/ksh93/sh/trestore.c) also needs changing.

This problem is also in 93u+, 93v- and ksh2020. Another one of those amazing bugs that have been there for decades. shcomp is basically not usable before this is fixed, unless you know the script does not contain any process substitutions.

**Comment by JohnoKing** [comment]
So far I've only been able to reproduce this bug if the process substitution is combined with a redirection. This makes me wonder if the bug is similar to #2.

**Comment by JohnoKing** [comment]
From what I've been able to debug, the bug/omission is probably in one of these functions:
https://github.com/ksh93/ksh/blob/56b530c43350cab061f194f93377f28f5388cee6/src/cmd/ksh93/sh/tdump.c#L157-L227

When `shcomp` handles a process substitution without a redirection, it reaches `p_comarg`. To handle the process substitution, `p_comarg` calls `p_arg`, which eventually calls `p_tree` to handle the commands in the process substitution:
https://github.com/ksh93/ksh/blob/56b530c43350cab061f194f93377f28f5388cee6/src/cmd/ksh93/sh/tdump.c#L222-L223
https://github.com/ksh93/ksh/blob/56b530c43350cab061f194f93377f28f5388cee6/src/cmd/ksh93/sh/tdump.c#L184-L185
Afaict `shcomp` does handle process substitutions correctly, unless one is combined with a redirection. In the bugged scenario, the `p_arg` call in the `else if` block is never reached. One idea I had for fixing this issue is to add a check for this scenario, but that alone doesn't fix the issue (it just causes a memory fault):
```diff
--- a/src/cmd/ksh93/sh/tdump.c
+++ b/src/cmd/ksh93/sh/tdump.c
@@ -219,7 +219,7 @@ static int p_comarg(register const struct comnod *com)
 	p_arg(com->comset);
 	if(!com->comarg)
 		sfputl(outfile,-1);
-	else if(com->comtyp&COMSCAN)
+	else if((com->comtyp&COMSCAN) || (com->comio && (com->comio->iofile & IOPROCSUB)))
 		p_arg(com->comarg);
 	else
 		p_comlist((struct dolnod*)com->comarg);
```

**Comment by JohnoKing** [comment]
Some more information relevant to this bug: when `shcomp` handles a redirection, the file given to the redirection is handled with `p_string`:
https://github.com/ksh93/ksh/blob/6b9703ffdd9a71c3fb7418ba7744fd734e39f454/src/cmd/ksh93/sh/tdump.c#L197-L201
When a normal file is passed to a redirection, `iop->ioname` points to the name of the file. For process substitutions `iop->ioname` is a newline:
```sh
$ cat ./hosts.sh
cat < /etc/hosts
$ hexdump -C <(shcomp ./hosts.sh)
00000000  0b 13 08 00 04 00 00 c0  00 0b 2f 65 74 63 2f 68  |........../etc/h|
00000010  6f 73 74 73 00 40 00 01  04 63 61 74 00 01        |osts.@...cat..|
0000001e

$ cat ./procsub.sh
cat < <(echo foo)
$ hexdump -C <(shcomp ./procsub.sh)
00000000  0b 13 08 00 04 00 00 a0  80 00 03 0a 02 00 40 00  |..............@.|
00000010  01 04 63 61 74 00 01                              |..cat..|
00000017
```

**Comment by McDutchie** [comment]
I've studied the code in io.c for executing process substitutions with redirections: https://github.com/ksh93/ksh/blob/6b9703ffdd9a71c3fb7418ba7744fd734e39f454/src/cmd/ksh93/sh/io.c#L1176-L1187

So, `iop->ioname` may start with '\n\0' and appear to be a string containing a newline, but it's actually a pointer to the parse tree for the process substitution and should be handled with a typecast to `struct argnod*`.

Based on that code, I've come up with the following provisional patch. It needs an extra hack to avoid the segfault in `p_arg()`. It does cause the command to be included in the shcomp output. Unfortunately, when trying to run it, ksh segfaults.

Note that the `sh_argprocsub()` call is not included because that causes a file name like `/dev/fd/4` to be included in the shcomp output instead of the process substitution's parse tree.

```diff
--- a/src/cmd/ksh93/sh/tdump.c
+++ b/src/cmd/ksh93/sh/tdump.c
@@ -219,6 +219,16 @@ static int p_comarg(register const struct comnod *com)
 	p_arg(com->comset);
 	if(!com->comarg)
 		sfputl(outfile,-1);
+	else if(com->comio && (com->comio->iofile & IOPROCSUB))
+	{
+		struct argnod *ap = (struct argnod*)stakalloc(ARGVAL+strlen(com->comio->ioname));
+		memset(ap, 0, ARGVAL);
+		if(com->comio->iofile & IOPUT)
+			ap->argflag = ARG_RAW;
+		ap->argchn.ap = (struct argnod*)com->comio->ioname;
+		((struct fornod*)ap->argchn.ap)->fornam = Empty; /* avoid segfault when calling strlen() in p_arg */
+		p_arg(ap);
+	}
 	else if(com->comtyp&COMSCAN)
 		p_arg(com->comarg);
 	else
```
This test script now compiles like this:
```
$ cat test.ksh
echo line 1
cat < <(echo line 2)
$ arch/*/bin/shcomp test.ksh >test.kshc
$ hexdump -C test.kshc
00000000  0b 13 08 00 04 00 00 40  00 03 05 65 63 68 6f 05  |.......@...echo.|
00000010  6c 69 6e 65 02 31 00 01  00 a0 80 00 03 0a 02 00  |line.1..........|
00000020  40 00 02 00 00 84 0a 00  40 00 03 05 65 63 68 6f  |@.......@...echo|
00000030  05 6c 69 6e 65 02 32 00  02 00 02                 |.line.2....|
0000003b
$ arch/*/bin/ksh test.kshc
line 1
Memory fault
```
Backtrace of the crash:
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib            0x00007fff5fa1113c _platform_strchr$VARIANT$Base + 28
1   ksh                                 0x0000000100a34486 sh_exec + 4918 (xec.c:1224)
2   ksh                                 0x00000001009bbde6 exfile + 3254 (main.c:586)
3   ksh                                 0x00000001009bcd30 sh_main + 3392 (main.c:358)
4   ksh                                 0x00000001009a1b36 main + 38 (pmain.c:45)
5   libdyld.dylib                       0x00007fff5f8283d5 start + 1
```
So it crashes here, in `strchr()`: https://github.com/ksh93/ksh/blob/6b9703ffdd9a71c3fb7418ba7744fd734e39f454/src/cmd/ksh93/sh/xec.c#L1224

That's as far as I got for now, I hope this is some progress.

**Comment by JohnoKing** [comment]
Implementing some handling for `IOPROCSUB` in trestore.c fixes the segfault, although process substitutions don't seem to work in the resulting script (also, in the patch below I've moved the `IOPROCSUB` handling in tdump.c to `p_redirect`). An improved patch probably should use the result of `r_arg`:
```diff
--- a/src/cmd/ksh93/sh/tdump.c
+++ b/src/cmd/ksh93/sh/tdump.c
@@ -197,6 +197,16 @@ static int p_redirect(register const struct ionod *iop)
 		else
 			sfputl(outfile,iop->iofile);
 		p_string(iop->ioname);
+		if(iop->iofile & IOPROCSUB)
+		{
+			struct argnod *ap = (struct argnod*)stakalloc(ARGVAL+strlen(iop->ioname));
+			memset(ap, 0, ARGVAL);
+			if(iop->iofile & IOPUT)
+				ap->argflag = ARG_RAW;
+			ap->argchn.ap = (struct argnod*)iop->ioname;
+			((struct fornod*)ap->argchn.ap)->fornam = Empty; /* avoid segfault when calling strlen() in p_arg */
+			p_arg(ap);
+		}
 		if(iop->iodelim)
 		{
 			p_string(iop->iodelim);
--- a/src/cmd/ksh93/sh/trestore.c
+++ b/src/cmd/ksh93/sh/trestore.c
@@ -225,6 +225,16 @@ static struct ionod *r_redirect(Shell_t* shp)
 			iopold->ionxt = iop;
 		iop->iofile = l;
 		iop->ioname = r_string(shp->stk);
+		if(iop->iofile & IOPROCSUB)
+		{
+			struct argnod *ap = (struct argnod*)stkalloc(shp->stk,ARGVAL+strlen(iop->ioname));
+			memset(ap, 0, ARGVAL);
+			if(iop->iofile & IOPUT)
+				ap->argflag = ARG_RAW;
+			ap->argchn.ap = (struct argnod*)iop->ioname;
+			((struct fornod*)ap->argchn.ap)->fornam = Empty;
+			r_arg(shp);
+		}
 		if(iop->iodelim = r_string(shp->stk))
 		{
 			iop->iosize = sfgetl(infile);
```
```sh
$ cat ./procsub.sh
echo line 1
cat < <(echo line 2)
echo line 3
$ arch/*/bin/ksh <(arch/*/bin/shcomp ./procsub.sh)
line 1
line 3
$ hexdump -C <(arch/*/bin/shcomp ./procsub.sh)
00000000  0b 13 08 00 04 00 00 40  00 03 05 65 63 68 6f 05  |.......@...echo.|
00000010  6c 69 6e 65 02 31 00 01  00 a0 80 00 03 0a 02 02  |line.1..........|
00000020  00 00 84 0a 00 40 00 03  05 65 63 68 6f 05 6c 69  |.....@...echo.li|
00000030  6e 65 02 32 00 02 00 00  40 00 01 04 63 61 74 00  |ne.2....@...cat.|
00000040  02 00 40 00 03 05 65 63  68 6f 05 6c 69 6e 65 02  |..@...echo.line.|
00000050  33 00 03                                          |3..|
00000053
```

**Comment by McDutchie** [comment]
**TODO:** after fixing this bug, change these regression tests back to using process substitutions. https://github.com/ksh93/ksh/blob/6701bb30decdb9ac984558fe08c7a9df0cd19ab9/src/cmd/ksh93/tests/builtins.sh#L988-L1005 https://github.com/ksh93/ksh/blob/6701bb30decdb9ac984558fe08c7a9df0cd19ab9/src/cmd/ksh93/tests/options.sh#L541-L545

**Comment by McDutchie** [comment]
If we can't fix this before releasing the beta then we can at least temporarily include this to prevent the generation of broken compiled scripts:
```diff
--- a/src/cmd/ksh93/sh/tdump.c
+++ b/src/cmd/ksh93/sh/tdump.c
@@ -219,6 +219,8 @@ static int p_comarg(register const struct comnod *com)
 	p_arg(com->comset);
 	if(!com->comarg)
 		sfputl(outfile,-1);
+	else if(com->comio && (com->comio->iofile & IOPROCSUB))
+		errormsg(SH_DICT,ERROR_exit(1),"process substitution as file name to redirection is not yet implemented for shcomp");
 	else if(com->comtyp&COMSCAN)
 		p_arg(com->comarg);
 	else
```

**Comment by JohnoKing** [comment]
This is minor, but error messages should be followed by `UNREACHABLE()` when they don't return:
```diff
--- a/src/cmd/ksh93/sh/tdump.c
+++ b/src/cmd/ksh93/sh/tdump.c
@@ -219,6 +219,11 @@ static int p_comarg(register const struct comnod *com)
 	p_arg(com->comset);
 	if(!com->comarg)
 		sfputl(outfile,-1);
+	else if(com->comio && (com->comio->iofile & IOPROCSUB))
+	{
+		errormsg(SH_DICT,ERROR_exit(1),"process substitution as file name to redirection is not yet implemented for shcomp");
+		UNREACHABLE();
+	}
 	else if(com->comtyp&COMSCAN)
 		p_arg(com->comarg);
 	else
```

On another note, I tested the patch and it causes the io.sh regression tests to fail under shcomp:
```
test io(shcomp) begins at 2021-04-21+13:16:12
/tmp/ksh93.shtests.3926.633/shcomp-io.ksh.orig: line 48: process substitution as file name to redirection is not yet implemented for shcomp
test io(shcomp) failed to compile at 2021-04-21+13:16:12 with exit code 1 [ 1 test 1 error ]
```

**Comment by McDutchie** [comment]
The line number in the error message is wrong, it's the line number of the last `alias` command -- which is explained by the fact that shcomp executes alias commands as it parses them.

Updated patch to give the correct line number:
```diff
--- a/src/cmd/ksh93/sh/tdump.c
+++ b/src/cmd/ksh93/sh/tdump.c
@@ -219,6 +219,12 @@ static int p_comarg(register const struct comnod *com)
 	p_arg(com->comset);
 	if(!com->comarg)
 		sfputl(outfile,-1);
+	else if(com->comio && (com->comio->iofile & IOPROCSUB))
+	{
+		error_info.line = com->comline;
+		errormsg(SH_DICT,ERROR_exit(1),"process substitution as file name to redirection is not yet implemented for shcomp");
+		UNREACHABLE();
+	}
 	else if(com->comtyp&COMSCAN)
 		p_arg(com->comarg);
 	else
```

This shows that the culprit is this command:

```
$ cat test.ksh
redirect 3<# ((40*8))
$ arch/darwin.i386-64/bin/shcomp test.ksh >/dev/null
test.ksh: line 1: process substitution as file name to redirection is not yet implemented for shcomp
```

That's clearly wrong. Our detection of a process substitution is broken.

**Comment by McDutchie** [comment]
The io.c code in [this comment](https://github.com/ksh93/ksh/issues/165#issuecomment-814087603) provided the clue. We need to exclude the `IOLSEEK` bit flag. This fixes it:
```diff
--- a/src/cmd/ksh93/sh/tdump.c
+++ b/src/cmd/ksh93/sh/tdump.c
@@ -219,6 +219,12 @@ static int p_comarg(register const struct comnod *com)
 	p_arg(com->comset);
 	if(!com->comarg)
 		sfputl(outfile,-1);
+	else if(com->comio && (com->comio->iofile & IOPROCSUB) && !(com->comio->iofile & IOLSEEK))
+	{
+		error_info.line = com->comline;
+		errormsg(SH_DICT,ERROR_exit(1),"process substitution as file name to redirection is not yet implemented for shcomp");
+		UNREACHABLE();
+	}
 	else if(com->comtyp&COMSCAN)
 		p_arg(com->comarg);
 	else
```
Now it seems to work:
```
$ cat test.ksh
redirect 3<# ((40*8))
cat < <(echo procsub)
$ arch/*/bin/shcomp test.ksh >/dev/null
test.ksh: line 2: process substitution as file name to redirection is not yet implemented for shcomp
$ bin/shtests -c io
#### Regression-testing /usr/local/src/ksh93/ksh/arch/darwin.i386-64/bin/ksh ####
test io(shcomp) begins at 2021-04-21+23:06:49
test io(shcomp) passed at 2021-04-21+23:06:52 [ 136 tests 0 errors ]
Total errors: 0
CPU time       user:      system:
main:      0m00.008s    0m00.020s
tests:     0m00.779s    0m00.866s
```

**Comment by McDutchie** [comment]
Hmm, no, it's still broken. Only the first redirection is checked for a process substitution. If any regular redirection precedes a redirection with a process substitution, the latter is ignored again.

This makes sense. The fix should probably be implemented in `p_redirect` which is called from `p_comarg`.

**Comment by McDutchie** [comment]
New patch:
```diff
--- a/src/cmd/ksh93/sh/tdump.c
+++ b/src/cmd/ksh93/sh/tdump.c
@@ -194,6 +194,11 @@ static int p_redirect(register const struct ionod *iop)
 	{
 		if(iop->iovname)
 			sfputl(outfile,iop->iofile|IOVNM);
+		else if((iop->iofile & IOPROCSUB) && !(iop->iofile & IOLSEEK))
+		{
+			errormsg(SH_DICT,ERROR_exit(1),"process substitution as file name to redirection is not yet implemented for shcomp");
+			UNREACHABLE();
+		}
 		else
 			sfputl(outfile,iop->iofile);
 		p_string(iop->ioname);
@@ -215,6 +220,7 @@ static int p_redirect(register const struct ionod *iop)
 
 static int p_comarg(register const struct comnod *com)
 {
+	error_info.line = com->comline;
 	p_redirect(com->comio);
 	p_arg(com->comset);
 	if(!com->comarg)
```
Now it does seem to be detected correctly:
```
$ cat test.ksh
redirect 3<# ((40*8))
cat >&2 < <(echo procsub)
$ arch/*/bin/shcomp test.ksh >/dev/null
test.ksh: line 2: process substitution as file name to redirection is not yet implemented for shcomp
```

**Comment by McDutchie** [comment]
I think I've fixed it. Once I started to understand some of this code, it was ridiculously simple. A process substitution as the argument to a redirection is encoded as a complete parse tree that is used as the file name for the redirection.
```diff
--- a/src/cmd/ksh93/sh/tdump.c
+++ b/src/cmd/ksh93/sh/tdump.c
@@ -196,7 +196,10 @@ static int p_redirect(register const struct ionod *iop)
 			sfputl(outfile,iop->iofile|IOVNM);
 		else
 			sfputl(outfile,iop->iofile);
-		p_string(iop->ioname);
+		if((iop->iofile & IOPROCSUB) && !(iop->iofile & IOLSEEK))
+			p_tree((Shnode_t*)iop->ioname);	/* process substitution as file name to redirection */
+		else
+			p_string(iop->ioname);		/* file name, descriptor, etc. */
 		if(iop->iodelim)
 		{
 			p_string(iop->iodelim);
--- a/src/cmd/ksh93/sh/trestore.c
+++ b/src/cmd/ksh93/sh/trestore.c
@@ -224,7 +224,10 @@ static struct ionod *r_redirect(Shell_t* shp)
 		else
 			iopold->ionxt = iop;
 		iop->iofile = l;
-		iop->ioname = r_string(shp->stk);
+		if((l & IOPROCSUB) && !(l & IOLSEEK))
+			iop->ioname = (char*)r_tree(shp);  /* process substitution as file name to redirection */
+		else
+			iop->ioname = r_string(shp->stk);  /* file name, descriptor, etc. */
 		if(iop->iodelim = r_string(shp->stk))
 		{
 			iop->iosize = sfgetl(infile);
```

After:
```
$ cat test.ksh                         
cat >&2 < <(echo procsub)
$ arch/*/bin/shcomp test.ksh >test.kshc 
$ arch/*/bin/ksh test.kshc
procsub
```

**Comment by JohnoKing** [comment]
~I think you closed this issue a little too soon. Output process substitutions with redirections still don't work with shcomp:~ **edit:** I was testing against the wrong git branch, see next comments below.
```sh
$ cat /tmp/bar
echo ok > >(sed 's/ok/good/g')
wait
$ arch/*/bin/ksh <(arch/*/bin/shcomp /tmp/bar)
$ arch/*/bin/ksh /tmp/bar                                 
good
```

**Comment by McDutchie** [comment]
> I think you closed this issue a little too soon. Output process substitutions with redirections still don't work with shcomp:
> 
> ```shell
> $ cat /tmp/bar
> echo ok > >(sed 's/ok/good/g')
> wait
> $ arch/*/bin/ksh <(arch/*/bin/shcomp /tmp/bar)
> $ arch/*/bin/ksh /tmp/bar                                 
> good
> ```

Are you sure? Your reproducer above works for me on macOS and Linux. An output process substitution is now also tested in io.sh and it passes on the CI runners.

You're using a process substitution to run the reproducer, which may confuse things. What shell and version are you using to invoke the reproducer? Do process substitutions work on it?

**Comment by JohnoKing** [comment]
Nevermind. I thought I was testing against the latest commit, but I was using the wrong git branch (which was one commit behind). I'm now using the correct git commit and process substitutions work fine with shcomp now. Feel free to close this issue.

**Comment by McDutchie** [comment]
Excellent. Thanks for keeping an eye on things.
