### ISSUE TITLE
Parse error during variable substitution

### ISSUE THREAD

**Issue by gkamat** [ksh93/ksh#290]
The closing quote does not appear to be registering during the parse of the following:
```
echo ${var:+'{}'}
```

Within a script, this will result in:
```
syntax error at line 1: `'' unmatched
```
This works correctly in the AST fork (`Version AJM 93u+ 2012-08-01`).

**Comment by JohnoKing** [comment]
Some quick testing shows this regression was introduced in commit 5ed9ffd6c.

**Comment by McDutchie** [comment]
This is also wrong:
```
$ echo ${var-{\}}
{}}
```
(expected: `{}`)

*edit:* As far as I can tell, this is a separate bug.

**Comment by McDutchie** [comment]
The problem is in the `}` character (whether `{` is present or not has no influence). It's the same for `-`, `+`, `:-` and `:+`.

```
$ arch/*/bin/ksh -c "echo \${var:-'}'}"
arch/darwin.i386-64/bin/ksh: syntax error at line 1: `'' unmatched
```

**Comment by McDutchie** [comment]
Removing the `continue;` here fixes this bug, but reintroduces the regressions fixed in 5ed9ffd6c49bbc7114b5762d7cb228f3e43dc8ab and 9f2066f146ae0d3ea733d9cccf5031273fb28e21. At this point I don't know how to fix both at once. https://github.com/ksh93/ksh/blob/090b65e79bd9e54edd2a6bfc67e3706850a5b5f9/src/cmd/ksh93/sh/lex.c#L994-L996

**Comment by McDutchie** [comment]
I've been experimenting with a new dedicated lexical state table for the `S_MOD1` case, to use instead of `ST_QUOTE`. The new table is the same as `ST_NESTED` (which is used for the `S_MOD2` case) except without a special meaning for `'`, `(`, `)`, or `~`. Please test this patch. @JohnoKing @hyenias 

<details><summary>Click to show patch</summary>

```diff
--- a/src/cmd/ksh93/data/lexstates.c
+++ b/src/cmd/ksh93/data/lexstates.c
@@ -387,6 +387,30 @@ static const char sh_lexstate9[256] =
 	0,	0,	0,	S_BRACE,S_PAT,	S_ENDCH,0,	0
 };
 
+/*
+ * ST_NESTED_MOD1
+ * for skipping over a string S in ${v-S}, ${v+S}, ${v:-S}, ${v:+S}
+ */
+static const char sh_lexstate11[256] =
+{
+	S_EOF,	0,	0,	0,	0,	0,	0,	0,
+	0,	S_BLNK,	S_NL,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	S_BLNK,	0,	S_QUOTE,0,	S_DOL,	0,	S_META,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	S_POP,	S_META,	0,	S_META,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	S_BRACT,S_ESC,	S_POP,	0,	0,
+	S_GRAVE,0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	S_BRACE,S_META,	S_POP,	0,	0
+};
+
 /*
  * This must be kept synchronous with all the above and the ST_* definitions in lexstates.h
  */
@@ -394,7 +418,7 @@ const char *sh_lexrstates[ST_NONE] =
 {
 	sh_lexstate0, sh_lexstate1, sh_lexstate2, sh_lexstate3,
 	sh_lexstate4, sh_lexstate5, sh_lexstate6, sh_lexstate7,
-	sh_lexstate8, sh_lexstate9, sh_lexstate5
+	sh_lexstate8, sh_lexstate9, sh_lexstate5, sh_lexstate11
 };
 
 
diff --git a/src/cmd/ksh93/include/lexstates.h b/src/cmd/ksh93/include/lexstates.h
index d1fbaee3..f23f2a91 100644
--- a/src/cmd/ksh93/include/lexstates.h
+++ b/src/cmd/ksh93/include/lexstates.h
@@ -79,7 +79,8 @@
 #define ST_DOLNAME	8
 #define ST_MACRO	9
 #define ST_QNEST	10
-#define ST_NONE		11
+#define ST_NESTED_MOD1	11
+#define ST_NONE		12
 
 #include "FEATURE/locale"
 
diff --git a/src/cmd/ksh93/sh/lex.c b/src/cmd/ksh93/sh/lex.c
index 14ef46ae..94ba40c0 100644
--- a/src/cmd/ksh93/sh/lex.c
+++ b/src/cmd/ksh93/sh/lex.c
@@ -992,7 +992,7 @@ int sh_lex(Lex_t* lp)
 				mode = ST_NESTED;
 				continue;
 			case S_MOD1:
-				mode = ST_QUOTE;
+				mode = ST_NESTED_MOD1;
 				continue;
 			case S_MOD2:
 #if SHOPT_KIA
diff --git a/src/cmd/ksh93/sh/macro.c b/src/cmd/ksh93/sh/macro.c
index ff839634..6fe542f6 100644
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -1659,7 +1659,7 @@ retry1:
 			}
 			else
 			{
-				sh_lexskip(lp, RBRACE, 0, sh_lexstates[ST_BRACE][c]==S_MOD1 ? ST_QUOTE : ST_NESTED);
+				sh_lexskip(lp, RBRACE, 0, sh_lexstates[ST_BRACE][c]==S_MOD1 ? ST_NESTED_MOD1 : ST_NESTED);
 				stkseek(stkp,offset);
 			}
 			argp=stkptr(stkp,offset);
diff --git a/src/cmd/ksh93/tests/quoting2.sh b/src/cmd/ksh93/tests/quoting2.sh
index 8fc4ce60..8d56211e 100755
--- a/src/cmd/ksh93/tests/quoting2.sh
+++ b/src/cmd/ksh93/tests/quoting2.sh
@@ -250,5 +250,13 @@ actual=$(printf %q $'1\x[11]1')
 [[ $actual == "$expect" ]] || err_exit 'shell-quoting: hex bytes not protected from subsequent hex-like chars' \
 				"(expected $expect; got $actual)"
 
+# ======
+# https://github.com/ksh93/ksh/issues/290
+var=dummy
+exp='{}'
+got=$(eval 'echo ${var:+'\''{}'\''}' 2>&1)
+[[ $got == "$exp" ]] || err_exit "Parse error during variable substitution" \
+	"(expected $(printf %q "$exp"), got $(printf %q "$got"))"
+
 # ======
 exit $((Errors<125?Errors:125))
```

</details>

**Comment by JohnoKing** [comment]
> I've been experimenting with a new dedicated lexical state table for the `S_MOD1` case, to use instead of `ST_QUOTE`.

That's an interesting idea. I've tested the patch and it does partially fix this bug, although the reproducer from https://github.com/ksh93/ksh/issues/290#issuecomment-828743840 still fails.

```
# 93u+m with the patch applied
$ arch/linux.i386-64/bin/ksh -c "echo \${var:+'{}'}"

$ arch/*/bin/ksh -c "echo \${var:-'}'}"
arch/linux.i386-64/bin/ksh: syntax error at line 1: `'' unmatched

# 93u+
$ ksh93u -c "echo \${var:+'{}'}"

$ ksh93u -c "echo \${var:-'}'}"
}
```

**Comment by McDutchie** [comment]
> That's an interesting idea. I've tested the patch and it does partially fix this bug, although the reproducer from [#290 (comment)](https://github.com/ksh93/ksh/issues/290#issuecomment-828743840) still fails.

This problem is fixed by reintroducing the special `S_LIT` meaning for `'` (position 39) in the new lexical state table. Unfortunately, doing that causes another regression, which I had fixed by removing that:
```
test quoting begins at 2021-04-29+20:18:03
	quoting.sh[189]: expansion of "{q:+'}" not correct when q unset
test quoting failed at 2021-04-29+20:18:04 with exit code 1 [ 94 tests 1 error ]
```
Here is the current patch, with that regression. No idea how to fix it yet.

<details><summary>Click to show patch</summary>

```diff
diff --git a/src/cmd/ksh93/data/lexstates.c b/src/cmd/ksh93/data/lexstates.c
index 41344f3c..afab5eb2 100644
--- a/src/cmd/ksh93/data/lexstates.c
+++ b/src/cmd/ksh93/data/lexstates.c
@@ -387,6 +387,30 @@ static const char sh_lexstate9[256] =
 	0,	0,	0,	S_BRACE,S_PAT,	S_ENDCH,0,	0
 };
 
+/*
+ * ST_NESTED_MOD1
+ * for skipping over a string S in ${v-S}, ${v+S}, ${v:-S}, ${v:+S}
+ */
+static const char sh_lexstate11[256] =
+{
+	S_EOF,	0,	0,	0,	0,	0,	0,	0,
+	0,	S_BLNK,	S_NL,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	S_BLNK,	0,	S_QUOTE,0,	S_DOL,	0,	S_META,	S_LIT,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	S_POP,	S_META,	0,	S_META,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	S_BRACT,S_ESC,	S_POP,	0,	0,
+	S_GRAVE,0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	S_BRACE,S_META,	S_POP,	0,	0
+};
+
 /*
  * This must be kept synchronous with all the above and the ST_* definitions in lexstates.h
  */
@@ -394,7 +418,7 @@ const char *sh_lexrstates[ST_NONE] =
 {
 	sh_lexstate0, sh_lexstate1, sh_lexstate2, sh_lexstate3,
 	sh_lexstate4, sh_lexstate5, sh_lexstate6, sh_lexstate7,
-	sh_lexstate8, sh_lexstate9, sh_lexstate5
+	sh_lexstate8, sh_lexstate9, sh_lexstate5, sh_lexstate11
 };
 
 
diff --git a/src/cmd/ksh93/include/lexstates.h b/src/cmd/ksh93/include/lexstates.h
index d1fbaee3..f23f2a91 100644
--- a/src/cmd/ksh93/include/lexstates.h
+++ b/src/cmd/ksh93/include/lexstates.h
@@ -79,7 +79,8 @@
 #define ST_DOLNAME	8
 #define ST_MACRO	9
 #define ST_QNEST	10
-#define ST_NONE		11
+#define ST_NESTED_MOD1	11
+#define ST_NONE		12
 
 #include "FEATURE/locale"
 
diff --git a/src/cmd/ksh93/sh/lex.c b/src/cmd/ksh93/sh/lex.c
index 14ef46ae..94ba40c0 100644
--- a/src/cmd/ksh93/sh/lex.c
+++ b/src/cmd/ksh93/sh/lex.c
@@ -992,7 +992,7 @@ int sh_lex(Lex_t* lp)
 				mode = ST_NESTED;
 				continue;
 			case S_MOD1:
-				mode = ST_QUOTE;
+				mode = ST_NESTED_MOD1;
 				continue;
 			case S_MOD2:
 #if SHOPT_KIA
diff --git a/src/cmd/ksh93/sh/macro.c b/src/cmd/ksh93/sh/macro.c
index ff839634..6fe542f6 100644
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -1659,7 +1659,7 @@ retry1:
 			}
 			else
 			{
-				sh_lexskip(lp, RBRACE, 0, sh_lexstates[ST_BRACE][c]==S_MOD1 ? ST_QUOTE : ST_NESTED);
+				sh_lexskip(lp, RBRACE, 0, sh_lexstates[ST_BRACE][c]==S_MOD1 ? ST_NESTED_MOD1 : ST_NESTED);
 				stkseek(stkp,offset);
 			}
 			argp=stkptr(stkp,offset);
diff --git a/src/cmd/ksh93/tests/quoting2.sh b/src/cmd/ksh93/tests/quoting2.sh
index 8fc4ce60..9471933b 100755
--- a/src/cmd/ksh93/tests/quoting2.sh
+++ b/src/cmd/ksh93/tests/quoting2.sh
@@ -250,5 +250,18 @@ actual=$(printf %q $'1\x[11]1')
 [[ $actual == "$expect" ]] || err_exit 'shell-quoting: hex bytes not protected from subsequent hex-like chars' \
 				"(expected $expect; got $actual)"
 
+# ======
+# https://github.com/ksh93/ksh/issues/290
+var=dummy
+exp='{}'
+got=$(eval 'echo ${var:+'\''{}'\''}' 2>&1)
+[[ $got == "$exp" ]] || err_exit "Parse error during variable substitution (1)" \
+	"(expected $(printf %q "$exp"), got $(printf %q "$got"))"
+unset var
+exp='}'
+got=$(eval 'echo ${var:-'\''}'\''}' 2>&1)
+[[ $got == "$exp" ]] || err_exit "Parse error during variable substitution (2)" \
+	"(expected $(printf %q "$exp"), got $(printf %q "$got"))"
+
 # ======
 exit $((Errors<125?Errors:125))
```

</details>

**Comment by McDutchie** [comment]
New patch, I think it's fixed. Please test this.

<details><summary>Click to show patch</summary>

```diff
--- a/src/cmd/ksh93/data/lexstates.c
+++ b/src/cmd/ksh93/data/lexstates.c
@@ -387,6 +387,30 @@ static const char sh_lexstate9[256] =
 	0,	0,	0,	S_BRACE,S_PAT,	S_ENDCH,0,	0
 };
 
+/*
+ * ST_MOD1
+ * for skipping over a string S in ${v-S}, ${v+S}, ${v:-S}, ${v:+S}
+ */
+static const char sh_lexstate11[256] =
+{
+	S_EOF,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	S_NL,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	S_QUOTE,0,	S_DOL,	0,	0,	S_LIT,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	S_ESC,	0,	0,	0,
+	S_GRAVE,0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	0,	0,	0,
+	0,	0,	0,	0,	0,	S_RBRA,	0,	0
+};
+
 /*
  * This must be kept synchronous with all the above and the ST_* definitions in lexstates.h
  */
@@ -394,7 +418,7 @@ const char *sh_lexrstates[ST_NONE] =
 {
 	sh_lexstate0, sh_lexstate1, sh_lexstate2, sh_lexstate3,
 	sh_lexstate4, sh_lexstate5, sh_lexstate6, sh_lexstate7,
-	sh_lexstate8, sh_lexstate9, sh_lexstate5
+	sh_lexstate8, sh_lexstate9, sh_lexstate5, sh_lexstate11
 };
 
 
--- a/src/cmd/ksh93/include/lexstates.h
+++ b/src/cmd/ksh93/include/lexstates.h
@@ -79,7 +79,8 @@
 #define ST_DOLNAME	8
 #define ST_MACRO	9
 #define ST_QNEST	10
-#define ST_NONE		11
+#define ST_MOD1		11
+#define ST_NONE		12
 
 #include "FEATURE/locale"
 
--- a/src/cmd/ksh93/sh/lex.c
+++ b/src/cmd/ksh93/sh/lex.c
@@ -992,7 +992,7 @@ int sh_lex(Lex_t* lp)
 				mode = ST_NESTED;
 				continue;
 			case S_MOD1:
-				mode = ST_QUOTE;
+				mode = ST_MOD1;
 				continue;
 			case S_MOD2:
 #if SHOPT_KIA
--- a/src/cmd/ksh93/tests/quoting2.sh
+++ b/src/cmd/ksh93/tests/quoting2.sh
@@ -250,5 +250,18 @@ actual=$(printf %q $'1\x[11]1')
 [[ $actual == "$expect" ]] || err_exit 'shell-quoting: hex bytes not protected from subsequent hex-like chars' \
 				"(expected $expect; got $actual)"
 
+# ======
+# https://github.com/ksh93/ksh/issues/290
+var=dummy
+exp='{}'
+got=$(eval 'echo ${var:+'\''{}'\''}' 2>&1)
+[[ $got == "$exp" ]] || err_exit "Parse error during variable substitution (1)" \
+	"(expected $(printf %q "$exp"), got $(printf %q "$got"))"
+unset var
+exp='}'
+got=$(eval 'echo ${var:-'\''}'\''}' 2>&1)
+[[ $got == "$exp" ]] || err_exit "Parse error during variable substitution (2)" \
+	"(expected $(printf %q "$exp"), got $(printf %q "$got"))"
+
 # ======
 exit $((Errors<125?Errors:125))
```

</details>

**Comment by JohnoKing** [comment]
I have yet to encounter any issues with the new patch.

**Comment by gkamat** [comment]
Unfortunately, the change does not completely fix the issue:
```
$ var=x; echo ${var:-'{}'}
x}
$ var=; echo ${var:+'{}'}
}
```

**Comment by McDutchie** [comment]
I think this fixes the remaining bug, please try.
```diff
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -1659,7 +1659,7 @@ retry1:
 			}
 			else
 			{
-				sh_lexskip(lp, RBRACE, 0, sh_lexstates[ST_BRACE][c]==S_MOD1 ? ST_QUOTE : ST_NESTED);
+				sh_lexskip(lp, RBRACE, 0, sh_lexstates[ST_BRACE][c]==S_MOD1 ? ST_MOD1 : ST_NESTED);
 				stkseek(stkp,offset);
 			}
 			argp=stkptr(stkp,offset);
```

**Comment by McDutchie** [comment]
I am not managing to break it now and I've added regression tests, so I'll close this again for now with the new fix. If you do still find breakage, please post again and I'll reopen it. Thanks for the testing and the reports.

**Comment by McDutchie** [comment]
Sigh. Because of the fix above, now [this regression](https://github.com/ksh93/ksh/issues/290#issuecomment-829522756) is back again.

~~I give up. I don't know how to fix this.~~

**Comment by McDutchie** [comment]
OK, maybe I actually do know how to fix this.

The problem causing that regression is that the `'` has a special meaning even within double-quoted strings. The original `ST_QUOTE` state table, where no quote character has any special meaning, is for avoiding this problem.

`ST_MOD1` is a copy of `ST_QUOTE` except the `'` has been given its special meaning back, which fixes this bug for non-quoted expansions.

So we need to combine this bug fix with a bit of code from the original ksh93, and use `ST_QUOTE` if the string is quoted (`mp->quote`) and we're not parsing a substitution that uses patterns where quotes are significant (`newops`).

```diff
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -1659,7 +1659,14 @@ retry1:
 			}
 			else
 			{
-				sh_lexskip(lp, RBRACE, 0, sh_lexstates[ST_BRACE][c]==S_MOD1 ? ST_MOD1 : ST_NESTED);
+				int state;
+				if(!newops && mp->quote)
+					state = ST_QUOTE;
+				else if(sh_lexstates[ST_BRACE][c]==S_MOD1)
+					state = ST_MOD1;
+				else
+					state = ST_NESTED;
+				sh_lexskip(lp, RBRACE, 0, state);
 				stkseek(stkp,offset);
 			}
 			argp=stkptr(stkp,offset);
```

**Comment by McDutchie** [comment]
A slightly shorter way of writing the same:
```diff
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -1659,7 +1659,12 @@ retry1:
 			}
 			else
 			{
-				sh_lexskip(lp, RBRACE, 0, sh_lexstates[ST_BRACE][c]==S_MOD1 ? ST_MOD1 : ST_NESTED);
+				int state;
+				if(sh_lexstates[ST_BRACE][c]==S_MOD1)
+					state = mp->quote ? ST_QUOTE : ST_MOD1;
+				else
+					state = ST_NESTED;
+				sh_lexskip(lp, RBRACE, 0, state);
 				stkseek(stkp,offset);
 			}
 			argp=stkptr(stkp,offset);
```
